"""Dagster asset, check, job and schedule definitions for SARVault.

Materializes the medallion lineage as an asset graph:

    raw (ChEMBL extract, multi-asset)        -.
    raw (UniChem / PDBe enrichment sources)  -+--> staging -> marts -> analytics
                                                  (dbt models, one asset each)

The dbt layer is loaded via ``dagster-dbt``: every dbt model becomes an asset and
every dbt test becomes an asset check, so the warehouse's existing data-quality
gate shows up natively in the Dagster UI. Two explicit checks are added on top for
a fast, orchestration-level smoke test of the built warehouse.

Run locally:
    dagster dev            # UI + lineage graph at http://localhost:3000

Materialise the transform layer from already-landed raw Parquet (the CI path):
    dagster job execute -j sarvault_transform -m orchestration.definitions
"""


import os
from pathlib import Path

import duckdb
from dagster import (
    AssetCheckResult,
    AssetExecutionContext,
    AssetKey,
    AssetOut,
    AssetSelection,
    Definitions,
    MaterializeResult,
    Output,
    ScheduleDefinition,
    asset,
    asset_check,
    define_asset_job,
    multi_asset,
)
from dagster_dbt import DbtCliResource, DbtProject, dbt_assets

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DBT_DIR = _REPO_ROOT / "dbt"
_PROFILES_DIR = _DBT_DIR / "profiles"

# ChEMBL-core raw tables produced in one pass by ``extract.run`` (activities are
# fetched first; molecules/targets/assays are derived from the activity IDs).
_CHEMBL_RAW_TABLES = ("activities", "molecules", "targets", "assays")

# The dbt source layer keys sources as ["raw", <table>] (see _sources.yml); the
# extract multi-asset below publishes exactly those keys so the graph connects.
_FACT_ACTIVITY = AssetKey(["marts", "fact_activity"])


def _raw_dir() -> Path:
    """Directory the extract layer lands Parquet into (env-overridable, as in dbt)."""
    return Path(os.environ.get("SARVAULT_RAW_DIR", "raw"))


def _warehouse_path() -> str:
    """DuckDB warehouse path, matching the dbt profile and the dashboard."""
    return os.environ.get("DUCKDB_PATH", "warehouse.duckdb")


# --- dbt project ----------------------------------------------------------------
# ``prepare_if_dev`` compiles the manifest under ``dagster dev``; in CI the
# manifest is generated by an explicit ``dbt parse`` step before Dagster loads.
dbt_project = DbtProject(project_dir=_DBT_DIR, profiles_dir=_PROFILES_DIR)
dbt_project.prepare_if_dev()


@dbt_assets(manifest=dbt_project.manifest_path)
def sarvault_dbt_assets(context: AssetExecutionContext, dbt: DbtCliResource):
    """Every dbt model as an asset; every dbt test as an asset check."""
    yield from dbt.cli(["build"], context=context).stream()


# --- raw extract (governed roots) ----------------------------------------------
@multi_asset(
    name="chembl_raw_extract",
    group_name="extract",
    outs={
        table: AssetOut(key=AssetKey(["raw", table]), is_required=True)
        for table in _CHEMBL_RAW_TABLES
    },
    compute_kind="chembl_api",
)
def chembl_raw_extract(context: AssetExecutionContext):
    """Fetch the scoped ChEMBL slice and land the four core raw Parquet datasets.

    Mirrors ``python -m extract.run``: one paginated, retry/backoff API pass with
    provenance columns. Only runs on a real materialisation - CI builds the
    transform layer from committed fixtures and never calls this asset.
    """
    from extract.run import run

    run()

    raw_dir = _raw_dir()
    for table in _CHEMBL_RAW_TABLES:
        path = raw_dir / f"raw_{table}.parquet"
        rows = duckdb.sql(f"select count(*) from read_parquet('{path}')").fetchone()[0]
        context.log.info(f"raw_{table}: {rows} rows -> {path}")
        yield Output(None, output_name=table, metadata={"rows": rows, "path": str(path)})


# --- cheminformatics compute (governed sources for the fingerprint/embedding models) --
@asset(
    key=AssetKey(["raw", "compound_cheminfo"]),
    deps=[AssetKey(["raw", "molecules"])],
    group_name="extract",
    compute_kind="rdkit",
)
def compound_cheminfo(context: AssetExecutionContext) -> MaterializeResult:
    """Derive ECFP4 fingerprints + Murcko scaffolds from the landed molecules.

    Deterministic given a pinned RDKit version; reads ``raw_molecules.parquet`` and
    lands ``raw_compound_cheminfo.parquet``, which the dbt cheminfo source reads.
    """
    from extract.cheminfo import main

    out = main(_raw_dir())
    rows = duckdb.sql(f"select count(*) from read_parquet('{out}')").fetchone()[0]
    context.log.info(f"cheminfo: {rows} rows -> {out}")
    return MaterializeResult(metadata={"rows": int(rows), "path": str(out)})


@asset(
    key=AssetKey(["raw", "compound_embedding"]),
    deps=[AssetKey(["raw", "compound_cheminfo"])],
    group_name="extract",
    compute_kind="umap",
)
def compound_embedding(context: AssetExecutionContext) -> MaterializeResult:
    """Fit a 2-D UMAP embedding over the ECFP4 fingerprints (deterministic seed).

    Reads ``raw_compound_cheminfo.parquet`` and lands ``raw_compound_embedding.parquet``.
    """
    from extract.embedding import main

    out = main(_raw_dir())
    rows = duckdb.sql(f"select count(*) from read_parquet('{out}')").fetchone()[0]
    context.log.info(f"embedding: {rows} rows -> {out}")
    return MaterializeResult(metadata={"rows": int(rows), "path": str(out)})


# --- explicit warehouse checks --------------------------------------------------
@asset_check(name="fact_activity_not_empty", asset=_FACT_ACTIVITY, blocking=True)
def fact_activity_not_empty() -> AssetCheckResult:
    """The fact table must contain at least one measured activity."""
    con = duckdb.connect(_warehouse_path(), read_only=True)
    try:
        rows = con.execute("select count(*) from main_marts.fact_activity").fetchone()[0]
    finally:
        con.close()
    return AssetCheckResult(passed=rows > 0, metadata={"rows": int(rows)})


@asset_check(name="pchembl_within_range", asset=_FACT_ACTIVITY, blocking=True)
def pchembl_within_range() -> AssetCheckResult:
    """Every non-null pChEMBL potency must sit in the physically plausible 0-14 band."""
    con = duckdb.connect(_warehouse_path(), read_only=True)
    try:
        bad = con.execute(
            """
            select count(*) from main_marts.fact_activity
            where pchembl_value is not null
              and (pchembl_value < 0 or pchembl_value > 14)
            """
        ).fetchone()[0]
    finally:
        con.close()
    return AssetCheckResult(passed=bad == 0, metadata={"out_of_range_rows": int(bad)})


# --- jobs & schedule ------------------------------------------------------------
# Full pipeline (extract -> transform); the nominal daily schedule targets it.
sarvault_pipeline = define_asset_job(
    name="sarvault_pipeline",
    selection=AssetSelection.all(),
    description="End-to-end: extract the scoped ChEMBL slice, then build + test the warehouse.",
)

# Transform-only: build + test the warehouse from already-landed raw Parquet.
# This is the deterministic CI path (fixtures on disk, no live API).
sarvault_transform = define_asset_job(
    name="sarvault_transform",
    selection=AssetSelection.assets(sarvault_dbt_assets),
    description="Build + test the dbt medallion from landed raw Parquet (CI path).",
)

# The source is a pinned snapshot, so scheduling is nominal - it exists to
# demonstrate DAG modelling and observability, not because ChEMBL updates often.
daily_refresh = ScheduleDefinition(
    name="daily_refresh",
    job=sarvault_pipeline,
    cron_schedule="0 3 * * *",
)


defs = Definitions(
    assets=[chembl_raw_extract, compound_cheminfo, compound_embedding, sarvault_dbt_assets],
    asset_checks=[fact_activity_not_empty, pchembl_within_range],
    jobs=[sarvault_pipeline, sarvault_transform],
    schedules=[daily_refresh],
    resources={"dbt": DbtCliResource(project_dir=dbt_project)},
)
